development:
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: admin
  database: posiback_dev
  host: localhost

staging:
  adapter: postgresql
  encoding: utf8
  database: posiback_stag
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: posiback_prod
  host: localhost
